# Generated by Django 4.2.11 on 2024-05-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.URLField()),
                ('genre', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('year_release', models.IntegerField()),
                ('metacritic_rating', models.FloatField()),
                ('runtime', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
